apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tdr-public-cms
  namespace: desarrollo
spec:
  tls:
    - hosts:
        - miportal.desa.dgrcorrientes.gov.ar
      secretName: portaldesa
  rules:
    - host: miportal.desa.dgrcorrientes.gov.ar
      http:
        paths:
          - path: /publiccms
            pathType: ImplementationSpecific
            backend:
              service:
                name: tdr-public-cms
                port:
                  number: 80